version: "3.7"

services:
  build-cloud-image:
    build:
      context: .
      dockerfile: build/cloud/Dockerfile
    image: cloud

  customer-database:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    image: mongo:4.0

  customer-read-api:
    build:
      args:
        service: customer-read-api
      context: build/service
    depends_on:
      - build-cloud-image
      - customer-database
    env_file:
      - configs/customer-database.env
    image: customer-read-api

  customer-worker:
    build:
      args:
        service: customer-worker
      context: build/service
    depends_on:
      - build-cloud-image
      - kafka
      - customer-database
    env_file:
      - configs/kafka.env
      - configs/customer-database.env
    environment:
      - KAFKA_GROUP_ID=customer-worker
    image: customer-worker
    restart: on-failure

  customer-write-api:
    build:
      args:
        service: customer-write-api
      context: build/service
    depends_on:
      - build-cloud-image
      - kafka
    env_file:
      - configs/kafka.env
    image: customer-write-api

  gateway:
    build:
      args:
        service: gateway
      context: build/service
    depends_on:
      - build-cloud-image
      - customer-read-api
      - customer-write-api
      - order-read-api
      - order-write-api
      - product-read-api
      - product-write-api
    environment:
      - CUSTOMER_READ_API_URL=http://customer-read-api:8080
      - CUSTOMER_WRITE_API_URL=http://customer-write-api:8080
      - ORDER_READ_API_URL=http://order-read-api:8080
      - ORDER_WRITE_API_URL=http://order-write-api:8080
      - PRODUCT_READ_API_URL=http://product-read-api:8080
      - PRODUCT_WRITE_API_URL=http://product-write-api:8080
    image: gateway
    ports:
      - 8080:8080

  kafka:
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_METADATA_MAX_AGE_MS=500
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    image: bitnami/kafka:2
    volumes:
      - "kafka-data:/bitnami"

  load-generator:
    build:
      args:
        service: load-generator
      context: build/service
    depends_on:
      - build-cloud-image
      - customer-write-api
      - product-write-api
    environment:
      - CUSTOMER_WRITE_API_URL=http://customer-write-api:8080
      - ORDER_WRITE_API_URL=http://order-write-api:8080
      - PRODUCT_WRITE_API_URL=http://product-write-api:8080
    image: load-generator

  order-database:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    image: mongo:4.0

  order-read-api:
    build:
      args:
        service: order-read-api
      context: build/service
    depends_on:
      - build-cloud-image
      - order-database
    env_file:
      - configs/order-database.env
    image: order-read-api

  order-worker:
    build:
      args:
        service: order-worker
      context: build/service
    depends_on:
      - build-cloud-image
      - kafka
      - order-database
    env_file:
      - configs/kafka.env
      - configs/order-database.env
    environment:
      - KAFKA_GROUP_ID=order-worker
    image: order-worker
    restart: on-failure

  order-write-api:
    build:
      args:
        service: order-write-api
      context: build/service
    depends_on:
      - build-cloud-image
      - kafka
    env_file:
      - configs/kafka.env
    image: order-write-api

  product-database:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    image: mongo:4.0

  product-read-api:
    build:
      args:
        service: product-read-api
      context: build/service
    depends_on:
      - build-cloud-image
      - product-database
    env_file:
      - configs/product-database.env
    image: product-read-api

  product-worker:
    build:
      args:
        service: product-worker
      context: build/service
    depends_on:
      - build-cloud-image
      - kafka
      - product-database
    env_file:
      - configs/kafka.env
      - configs/product-database.env
    environment:
      - KAFKA_GROUP_ID=product-worker
    image: product-worker
    restart: on-failure

  product-write-api:
    build:
      args:
        service: product-write-api
      context: build/service
    depends_on:
      - build-cloud-image
      - kafka
    env_file:
      - configs/kafka.env
    image: product-write-api

  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  kafka-data:
    driver: local

  zookeeper-data:
    driver: local
