// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductInput struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type Product struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}
