// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCustomerInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type CreateOrderInput struct {
	CustomerID string           `json:"customerID"`
	LineItems  []*LineItemInput `json:"lineItems"`
}

type CreateProductInput struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type Customer struct {
	FirstName string `json:"firstName"`
	ID        string `json:"id"`
	LastName  string `json:"lastName"`
}

type LineItemInput struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}
