name: Build

on: [push]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build services
        run: docker-compose build
      - name: Start services
        run: docker-compose up -d
      - name: Run integration tests
        run: docker-compose up --abort-on-container-exit --exit-code-from integration integration
        working-directory: test

  system-tests:
    name: System Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build services
        run: docker-compose build
      - name: Start services
        run: docker-compose up -d
      - name: Run system tests
        run: docker-compose up --abort-on-container-exit --exit-code-from system system
        working-directory: test
